version: '3.8'

services:
    postgres-db:
        image: postgres:15.3
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', '${DATABASE_USERNAME}']
            interval: 10s
            timeout: 5s
            retries: 5
